site_name: Software Engineering
site_url: https://uselessscat.github.io/software-engineering/
repo_url: https://github.com/uselessscat/software-engineering
edit_uri: edit/main/docs/

docs_dir: docs

watch:
  - docs
  - overrides

theme:
  name: material
  custom_dir: overrides
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.footer.last-updated
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - awesome-pages
  - strip-number-prefix:
      pattern: "^\\d+-"
      strict: true
      strip_links: false
  - i18n:
      docs_structure: folder
      fallback_to_default: false
      languages:
        - locale: es
          name: Espa√±ol
          default: true
        - locale: en
          name: English
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
#  - kroki:
#      ServerURL: http://localhost:8001
#      FileTypes:
#        - svg
#      TagFormat: svg
#      HttpMethod: POST
#  - with-pdf
  - search

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.25/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.25/dist/contrib/auto-render.min.js
  - https://cdn.jsdelivr.net/npm/@panzoom/panzoom@4.6.0/dist/panzoom.min.js
  - assets/javascripts/katex-init.js
#  - js/kroki-viewer.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.25/dist/katex.min.css
  - assets/stylesheets/lists.css
  - assets/stylesheets/tables.css
#  - css/kroki-viewer.css
